create table if not exists public.entitlements (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  item_type text not null default 'species',
  item_key text not null,
  source text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.entitlements
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists item_type text not null default 'species',
  add column if not exists item_key text,
  add column if not exists source text,
  add column if not exists active boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists entitlements_user_item_unique
on public.entitlements (user_id, item_type, item_key);

alter table public.entitlements enable row level security;

drop policy if exists "entitlements_select_own" on public.entitlements;
create policy "entitlements_select_own"
on public.entitlements
for select
to authenticated
using (user_id = auth.uid());

grant select on public.entitlements to authenticated;
grant select, insert, update, delete on public.entitlements to service_role;

create table if not exists public.equipped_cosmetics (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  slot text not null,
  item_key text not null,
  updated_at timestamptz not null default now()
);

alter table public.equipped_cosmetics
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists slot text,
  add column if not exists item_key text,
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists equipped_cosmetics_user_slot_unique
on public.equipped_cosmetics (user_id, slot);

alter table public.equipped_cosmetics enable row level security;

drop policy if exists "equipped_cosmetics_select_own" on public.equipped_cosmetics;
create policy "equipped_cosmetics_select_own"
on public.equipped_cosmetics
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "equipped_cosmetics_upsert_own" on public.equipped_cosmetics;
create policy "equipped_cosmetics_upsert_own"
on public.equipped_cosmetics
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

grant select, insert, update, delete on public.equipped_cosmetics to authenticated;
grant select, insert, update, delete on public.equipped_cosmetics to service_role;
